### ISSUE TITLE
 Responsive Design Improvements

### ISSUE THREAD

**Issue by franciscoaiolfi** [brasiliapp/web#1]
I will make some adjustments to enhance the responsiveness of this page component.
 
Imagens inseridas via drive.

https://drive.google.com/drive/folders/1rXrJN0Icl2fTJKJnWCM6YUbAVOUWkvrw?usp=sharing

@viictorcamposs ajustei aqui amigo.

**Comment by viictorcamposs** [comment]
@franciscoaiolfi os links estão funcionando pra vc?? aqui p mim é redirecionado de volta pra issues do projeto
