### ISSUE TITLE
Abaixo do total das despesas categorizar o montante de cada tipo

### ISSUE THREAD

**Issue by aniltonveiga** [brasiliapp/web#13]
## Objetivo

Categorizar as despesas dos deputados abaixo do total do mês

## Como
Uma lista vertical com cards do tailwind ou do nextUi (https://nextui.org/docs/components/card) contendo o total da categoria da despesa (expenses.tipoDespesa) e sua descrição (Ex: R$ 12.000,   passagens aéreas) existe um método dentro da pasta [utils/index.js function CalculateTotal](https://github.com/brasiliapp/web/blob/main/utils/index.js#L75) que só precisa passar um array e a propriedade que deseja somar que retorna o valor.

## Onde esta o dado
O objeto de despesas (expenses) possui uma propriedade tipoDespesa.

## Exemplo
Dentro do App deprecado existia a seção "Categorias de gastos"

![image](https://github.com/brasiliapp/web/assets/2703782/651cb14c-a43f-4987-8b6c-8deeeb994f31)

## Mais contextos sobre os tipos de despesas
1 - passagens aéreas;

2 – telefones dos gabinetes, dos escritórios nos estados e dos imóveis funcionais, e as despesas com o celular funcional do deputado. As contas devem ser de comprovada responsabilidade do parlamentar;

3 - manutenção de escritórios de apoio à atividade parlamentar, como locação de imóveis, energia elétrica, água e esgoto, acesso à internet, entre outros;

4 - alimentação do deputado;

5 – hospedagem, exceto no Distrito Federal;

6 - despesas com locomoção por:

- locação ou fretamento de aeronaves;

- locação ou fretamento de veículos automotores (limite inacumulável de R$ 12.713,00 mensais), permitida contratação de seguro;

- locação ou fretamento de embarcações;

- serviços de táxi, pedágio e estacionamento (limite inacumulável de R$ 2.700,00 mensais);

- passagens terrestres, marítimas ou fluviais.

7- combustíveis e lubrificantes (limite inacumulável de R$ 9.392,00 mensais);

8 - serviços de segurança de empresas especializadas (limite inacumulável de R$ 8.700,00 mensais);

9 - divulgação da atividade parlamentar (exceto nos 120 dias anteriores à data das eleições, se o deputado for candidato - [Ato da Mesa 40/2012](https://www2.camara.leg.br/legin/int/atomes/2012/atodamesa-40-20-abril-2012-612850-norma-cd-mesa.html);

10 - participação em cursos, congressos ou eventos, realizados por instituição especializada (limite mensal inacumulável de 25% do valor da menor cota – hoje R$7.697,17);

11 - complementação de auxílio-moradia, de acordo com o [Ato da Mesa 104/88](https://www2.camara.leg.br/legin/int/atomes/1988/atodamesa-104-1-dezembro-1988-320535-norma-cd-mesa.html) (limite inacumulável de R$ 4.148,80 mensais).

[Mais informações](https://www2.camara.leg.br/comunicacao/assessoria-de-imprensa/guia-para-jornalistas/cota-parlamentar)

**Comment by matmatias** [comment]
PR: #15
