### ISSUE TITLE
Implement cnpj information from brasiliapi

### ISSUE THREAD

**Issue by aniltonveiga** [brasiliapp/web#39]
The Brasilapi project (https://brasilapi.com.br/) maintains open and free information about CNPJ such as: opening date, registration status, and partners.

<img width="596" alt="image" src="https://github.com/brasiliapp/web/assets/2703782/a7500e11-b364-462c-bb08-b837dbc6362e">

For BrasiliApp, this information is important, as it is known that many politicians hire front companies, or companies belonging to relatives, to perform services.

## Como
When clicking on the 'Verificar' button, make a request to:
`https://brasilapi.com.br/api/cnpj/v1/{CNPJ}`
Entering the company's CNPJ without dots or dashes.

### In the response of this request will require the use of the following properties:
- razao_social
- nome_fantasia
- capital_social
- data_inicio_atividade
- descricao_situacao_cadastral
- qsa (Sócios da empresa)

**Comment by raulcesar54** [comment]
Feature added in PR https://github.com/brasiliapp/web/pull/40
