### ISSUE TITLE
Ajustar url para o website na descrição do projeto

### ISSUE THREAD

**Issue by matmatias** [brasiliapp/web#4]
A URL na descrição no projeto está quebrada, pois está faltando uma barra em https:/

Versão atual: [https:/brasiliapp.com.br](https:/brasiliapp.com.br)
Versão cirrigida: [https://brasiliapp.com.br](https://brasiliapp.com.br)

**Comment by aniltonveiga** [comment]
PR #5

**Comment by matmatias** [comment]
@aniltonveiga o link quebrado está no "About" do Github, não tenho permissão para alterar, somente você.

![image](https://github.com/brasiliapp/web/assets/38060185/f99c3e1d-3335-4ea8-af4a-834dca1e9b36)

**Comment by aniltonveiga** [comment]
@matmatias alterado :)
