### ISSUE TITLE
Tabela de deputados federais em /deputado-federal desalinhada

### ISSUE THREAD

**Issue by matmatias** [brasiliapp/web#6]
A tabela de deputados federais está desalinhada, e a foto de cada deputado está cortada na região de suas cabeças, conforme a imagem abaixo:

![image](https://github.com/brasiliapp/web/assets/38060185/17541bfb-f499-4d7c-8311-072e97f8050d)

**Comment by franciscoaiolfi** [comment]
@matmatias  Eu dei uma observada nisso, a parte da foto ali é que usa um cara chamado avatarProps, e quando passamos um objetct-fit nele, ele passa para o span que faz um wrapper nessa imagem. Atualmente não tem uma props de object-fit no avatarProps dessa lib. Mas é uma boa arrumar isso.

**Comment by matmatias** [comment]
@franciscoaiolfi dá para sobrescrever as classes de <img/> passando o objeto { img: "object-fill" } para a propriedade classNames da prop avatarProps, do componente User.

**Comment by matmatias** [comment]
PR: #9.
